config/routes.rb
Rails.application.routes.draw do
  # This line mounts Solidus's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted,
  # simply change the :at option to something different.
  # We ask that you don't use the :as option here,
  # as Solidus relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'

  namespace :potepan do
    get '/',                        to: 'sample#index'
    get 'index',                    to: 'sample#index'
    get :product_grid_left_sidebar, to: 'sample#product_grid_left_sidebar'
    get :product_list_left_sidebar, to: 'sample#product_list_left_sidebar'
    get :single_product,            to: 'sample#single_product'
    get :cart_page,                 to: 'sample#cart_page'
    get :checkout_step_1,           to: 'sample#checkout_step_1'
    get :checkout_step_2,           to: 'sample#checkout_step_2'
    get :checkout_step_3,           to: 'sample#checkout_step_3'
    get :checkout_complete,         to: 'sample#checkout_complete'
    get :blog_left_sidebar,         to: 'sample#blog_left_sidebar'
    get :blog_right_sidebar,        to: 'sample#blog_right_sidebar'
    get :blog_single_left_sidebar,  to: 'sample#blog_single_left_sidebar'
    get :blog_single_right_sidebar, to: 'sample#blog_single_right_sidebar'
    get :about_us,                  to: 'sample#about_us'
    get :tokushoho,                 to: 'sample#tokushoho'
    get :privacy_policy,            to: 'sample#privacy_policy'
    resources :products,            :only => :show
    resources :taxons,              :only => :show, :as => :categories, :path => 'categories'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/potepan/product_decorator.rb
Spree::Product.class_eval do
  scope :includes_price_images, -> { includes(master: [:default_price, :images]) }
  scope :related_products, -> (current_product) do
    joins(:taxons).where(spree_taxons: { id: current_product.taxons.ids })
  end
  scope :except_duplication_products, -> (current_product) do
    where.not(id: current_product.id).distinct
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/potepan/products_controller.rb
class Potepan::ProductsController < ApplicationController
  def show
    @product = Spree::Product.includes(product_properties: :property).friendly.find(params[:id])
    if @product.variants.any?
      @variant = params[:variant_id] ? @product.variants.find(params[:variant_id]) : @product.variants.first
    else
      @variant = @product.master
    end
    @related_products = Spree::Product.
      includes_price_images.
      related_products(@product).
      except_duplication_products(@product).
      sample(4)
  end
end

app/controllers/potepan/sample_controller.rb
class Potepan::SampleController < ApplicationController
  def index
  end

  def product_grid_left_sidebar
  end

  def product_list_left_sidebar
  end

  def single_product
  end

  def cart_page
  end

  def checkout_step_1
  end

  def checkout_step_2
  end

  def checkout_step_3
  end

  def checkout_complete
  end

  def blog_left_sidebar
  end

  def blog_right_sidebar
  end

  def blog_single_left_sidebar
  end

  def blog_single_right_sidebar
  end

  def about_us
  end

  def tokushoho
  end

  def privacy_policy
  end
end

app/controllers/potepan/taxons_controller.rb
class Potepan::TaxonsController < ApplicationController
  def show
    @taxons = Spree::Taxon.all
    @taxon = Spree::Taxon.find(params[:id])
    @products = Spree::Product.in_taxon(@taxon).includes_price_images
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = "BIGBAG Store"
    if page_title.blank?
      base_title
    else
      "#{page_title} - #{base_title}"
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  def product_and_variant_images(product, variant)
    product_images = product.images.to_a
    product_images += variant.images unless variant.is_master
    product_images
  end

  def show_main_image(image, i)
    content_tag(:div, class: "item #{'active' if i == 0}", data: { thumb: i }) do
      image_tag(image.attachment.url(:large))
    end
  end

  def show_thum_image(image, i)
    content_tag(:div, class: 'thumb', data: { target: '#carousel', slide_to: i }) do
      image_tag(image.attachment.url(:small))
    end
  end
end

app/views/layouts/_footer.html.erb
<!-- FOOTER -->
<div class="footer clearfix">
  <div class="container">
    <div class="row">
      <div class="col-sm-2 col-xs-12">
        <div class="footerLink">
          <h5>商品をお探しなら</h5>
          <ul class="list-unstyled">
            <li><a href="product-grid-left-sidebar.html">SHOES</a></li>
            <li><a href="product-grid-left-sidebar.html">BAGS </a></li>
            <li><a href="product-grid-left-sidebar.html">GLASSES </a></li>
          </ul>
        </div>
      </div>
      <div class="col-sm-2 col-xs-12">
        <div class="footerLink">
          <h5>BIGBAGについて</h5>
          <ul class="list-unstyled">
            <li><a href="about-us.html">ABOUT US</a></li>
            <li><a href="privacy-policy.html">プライバシーポリシー</a></li>
            <li><a href="tokushoho.html">特定商取引法についての表記</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- COPY RIGHT -->
<div class="copyRight clearfix">
  <div class="container">
    <div class="row">
      <div class="col-sm-7 col-xs-12">
        <p>&copy; 2017 Copyright Potepan Store .</p>
      </div>
      <div class="col-sm-5 col-xs-12">
        <ul class="list-inline">
          <li><a href="#"><i class="fa fa-twitter"></i></a></li>
          <li><a href="#"><i class="fa fa-facebook"></i></a></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_modal.html.erb
<!-- LOGIN MODAL -->
<div class="modal fade login-modal" id="login" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title">ログイン</h3>
      </div>
      <div class="modal-body">
        <form action="login-" method="POST" role="form">
          <div class="form-group">
            <label for="login-email">メールアドレス</label>
            <input type="email" class="form-control" id="login-email">
          </div>
          <div class="form-group">
            <label for="login-password">パスワード</label>
            <input type="password" class="form-control" id="login-password">
          </div>
          <div class="checkbox">
            <label>
              <input type="checkbox"> 記憶しておく
            </label>
          </div>
          <button type="submit" class="btn btn-primary btn-block">ログイン</button>
          <a href="lost-password.html" class="btn btn-link btn-block">パスワードをお忘れの方</a>
        </form>
      </div>
    </div>
  </div>
</div>

<!-- SIGN UP MODAL -->
<div class="modal fade" id="signup" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title">新規登録</h3>
      </div>
      <div class="modal-body">
        <form action="" method="POST" role="form">
          <div class="form-group">
            <label for="signup-email">メールアドレス</label>
            <input type="email" class="form-control" id="signup-email">
          </div>
          <div class="form-group">
            <label for="signup-password">パスワード</label>
            <input type="password" class="form-control" id="signup-password">
          </div>
          <div class="form-group">
            <label for="signup-password-confirmation">パスワード（確認用）</label>
            <input type="password" class="form-control" id="signup-password-confirmation">
          </div>
          <button type="submit" class="btn btn-primary btn-block">登録する</button>
        </form>
      </div>
    </div>
  </div>
</div>

<!-- PRODUCT QUICK VIEW MODAL -->
<% if request.path == potepan_path || potepan_index_path || potepan_product_grid_left_sidebar_path || potepan_product_list_left_sidebar_path || potepan_single_product_path || potepan_product_path %>
  <div class="modal fade quick-view" tabindex="-1" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-body">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <div class="media">
            <div class="media-left">
              <%= image_tag("products/quick-view/quick-view-01.jpg", :class => "media-object", :alt => "Image") %>
            </div>
            <div class="media-body">
              <h2>Old Skool Navy</h2>
              <h3>149円</h3>
              <p>Classic sneaker from Vans. Cotton canvas and suede upper. Textile lining with heel stabilizer and ankle support. Contrasting laces. Sits on a classic waffle rubber sole.</p>
              <span class="quick-drop">
                <select name="guiest_id3" id="guiest_id3" class="select-drop">
                  <option value="0">S</option>
                  <option value="1">M</option>
                  <option value="2">L</option>
                  <option value="3">XL</option>
                </select>
              </span>
              <span class="quick-drop resizeWidth">
                <select name="guiest_id4" id="guiest_id4" class="select-drop">
                  <option value="1">1</option>
                  <option value="2">2</option>
                  <option value="3">3</option>
                </select>
              </span>
              <div class="btn-area">
                <a href="cart_page.html" class="btn btn-primary btn-block">カートへ入れる <i class="fa fa-angle-right" aria-hidden="true"></i></a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <!-- SITE TITTLE -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <!-- PLUGINS CSS STYLE -->
    <%= stylesheet_link_tag "application", :media => "all" %>
    <!-- GOOGLE FONT -->
    <%= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Oxygen:400,300,700', :media => "all" %>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css" rel="stylesheet">
  </head>
  <body>
    <div class="main-wrapper">
      <%= render 'layouts/header' %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
    <%= render 'layouts/modal' %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/potepan/products/show.html.erb
<% provide(:title, "#{@product.name}") %>
<!-- LIGHT SECTION -->
<section class="lightSection clearfix pageHeader">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <div class="page-title">
          <h2><%= @product.name %></h2>
        </div>
      </div>
      <div class="col-xs-6">
        <ol class="breadcrumb pull-right">
          <li><a href="index.html">Home</a></li>
          <li class="active"><%= @product.name %></li>
        </ol>
      </div>
    </div>
  </div>
</section>
<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix">
  <div class="container">
    <div class="row singleProduct">
      <div class="col-xs-12">
        <div class="media">
          <div class="media-left productSlider">
            <div id="carousel" class="carousel slide" data-ride="carousel">
              <div class="carousel-inner">
                <% product_and_variant_images(@product, @variant).each_with_index do |image, i| %>
                  <%= show_main_image(image, i) %>
                <% end %>
              </div>
            </div>
            <div class="clearfix">
              <div id="thumbcarousel" class="carousel slide" data-interval="false">
                <div class="carousel-inner">
                  <% product_and_variant_images(@product, @variant).each_with_index do |image, i| %>
                    <%= show_thum_image(image, i) %>
                  <% end %>
                </div>
                <a class="left carousel-control" href="#thumbcarousel" role="button" data-slide="prev">
                  <span class="glyphicon glyphicon-chevron-left"></span>
                </a>
                <a class="right carousel-control" href="#thumbcarousel" role="button" data-slide="next">
                  <span class="glyphicon glyphicon-chevron-right"></span>
                </a>
              </div>
            </div>
          </div>
          <div class="media-body">
            <ul class="list-inline">
              <li>
                <%= link_to(potepan_product_grid_left_sidebar_path) do %>
                  <i class="fa fa-reply" aria-hidden="true"></i>一覧ページへ戻る
                <% end %>
              </li>
            </ul>
            <h2><%= @product.name %></h2>
            <h3>$<%= @variant.price%></h3>
            <p><%= @product.description %></p>
            <% if @product.variants.any? %>
              <span class="quick-drop">
                <%= form_tag(potepan_product_path, method: :get, :id => 'select_form') do %>
                  <%= select_tag 'variant_id',options_from_collection_for_select(@product.variants, :id, :options_text, @variant.id), :id => 'guiest_id3', :class => 'select-drop select-option' %>
                <% end %>
              </span>
            <% end %>
            <span class="quick-drop resizeWidth">
              <select name="guiest_id4" id="guiest_id4" class="select-drop">
                <% @variant.stock_items.first.count_on_hand.times do |num| %>
                  <option value="<%= num + 1 %>"><%= num + 1 %></option>
                <% end %>
              </select>
            </span>
            <div class="btn-area">
              <a href="cart_page.html" class="btn btn-primary btn-block">カートへ入れる<i class="fa fa-angle-right" aria-hidden="true"></i></a>
            </div>
            <div class="tabArea">
              <ul class="nav nav-tabs">
                <li class="active"><a data-toggle="tab" href="#details">details</a></li>
                <li><a data-toggle="tab" href="#about-art">about art</a></li>
                <li><a data-toggle="tab" href="#sizing">sizing</a></li>
                <li><a data-toggle="tab" href="#shipping">shipping</a></li>
              </ul>
              <div class="tab-content">
                <div id="details" class="tab-pane fade in active">
                  <ul class="list-unstyled">
                    <% @product.product_properties.each do |product_property| %>
                      <li><%= product_property.property.presentation %> : <%= product_property.value %></li>
                    <% end %>
                  </ul>
                </div>
                <div id="about-art" class="tab-pane fade">
                  <p>Nulla facilisi. Mauris efficitur, massa et iaculis accumsan, mauris velit ultrices purus, quis condimentum nibh dolor ut tortor. Donec egestas tortor quis mattis gravida. Ut efficitur elit vitae dignissim volutpat. </p>
                </div>
                <div id="sizing" class="tab-pane fade">
                  <p>Praesent dui felis, gravida a auctor at, facilisis commodo ipsum. Cras eu faucibus justo. Nullam varius cursus nisi, sed elementum sem sagittis at. Nulla tellus massa, vestibulum a commodo facilisis, pulvinar convallis nunc.</p>
                </div>
                <div id="shipping" class="tab-pane fade">
                  <p>Mauris lobortis augue ex, ut faucibus nisi mollis ac. Sed volutpat scelerisque ex ut ullamcorper. Cras at velit quis sapien dapibus laoreet a id odio. Sed sit amet accumsan ante, eu congue metus. Aenean eros tortor, cursus quis feugiat sed, vestibulum vel purus.</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <% if @related_products.presence %>
      <div class="row productsContent">
        <div class="col-xs-12">
          <div class="page-header">
            <h4>関連商品</h4>
          </div>
        </div>
        <% @related_products.each do |product| %>
          <div class="col-md-3 col-sm-6 col-xs-12">
            <div class="productBox">
              <div class="productImage clearfix">
                <%= image_tag(product.display_image.attachment.url(:product), alt: product.display_image.alt) %>
                <div class="productMasking">
                  <ul class="list-inline btn-group" role="group">
                    <li><a data-toggle="modal" href=".login-modal" class="btn btn-default"><i class="fa fa-heart"></i></a></li>
                    <li><a href="cart_page.html" class="btn btn-default"><i class="fa fa-shopping-cart"></i></a></li>
                    <li><a class="btn btn-default" data-toggle="modal" href=".quick-view" ><i class="fa fa-eye"></i></a></li>
                  </ul>
                </div>
              </div>
              <div class="productCaption clearfix">
              <%= link_to potepan_product_path(product.id) do %>
                <h5><%= product.name %></h5>
              <% end %>
              <h3><%= product.display_price %></h3>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</section>

app/views/potepan/sample/cart_page.html.erb
<% provide(:title, "Cart Page") %>
<!-- LIGHT SECTION -->
<section class="lightSection clearfix pageHeaderImage">
  <div class="container">
    <div class="tableBlock">
      <div class="row tableInner">
        <div class="col-xs-12">
          <div class="page-title">
            <h2>cart</h2>
            <ol class="breadcrumb">
              <li>
                <a href="index.html">Home</a>
              </li>
              <li class="active">cart</li>
            </ol>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix cartListWrapper">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="cartListInner">
          <form action="#">
            <div class="table-responsive">
              <table class="table">
                <thead>
                  <tr>
                    <th></th>
                    <th>商品名</th>
                    <th>価格</th>
                    <th>数</th>
                    <th>小計</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td class="col-xs-2">
                      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                      <span class="cartImage"><%= image_tag("img/products/cart-image.jpg", :alt => "image") %></span>
                    </td>
                    <td class="col-xs-4">Italian Winter Hat</td>
                    <td class="col-xs-2">99円</td>
                    <td class="col-xs-2"><input type="text" placeholder="1"></td>
                    <td class="col-xs-2">99円</td>
                  </tr>
                  <tr>
                    <td class="col-xs-2">
                      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                      <span class="cartImage"><%= image_tag("img/products/cart-image.jpg", :alt => "image") %></span>
                    </td>
                    <td class="col-xs-4">Italian Winter Hat</td>
                    <td class="col-xs-2">99円</td>
                    <td class="col-xs-2"><input type="text" placeholder="1"></td>
                    <td class="col-xs-2">99円</td>
                  </tr>
                  <tr>
                    <td class="col-xs-2">
                      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                      <span class="cartImage"><%= image_tag("img/products/cart-image.jpg", :alt => "image") %></span>
                    </td>
                    <td class="col-xs-4">Italian Winter Hat</td>
                    <td class="col-xs-2">99円</td>
                    <td class="col-xs-2"><input type="text" placeholder="1"></td>
                    <td class="col-xs-2">99円</td>
                  </tr>
                </tbody>
              </table>
            </div>
            <div class="updateArea">
             <!--  <div class="input-group">
                <input type="text" class="form-control" placeholder="I have a discount coupon" aria-describedby="basic-addon2">
                <a href="#" class="btn input-group-addon" id="basic-addon2">apply coupon</a>
              </div> -->
              <a href="#" class="btn">アップデート</a>
            </div>
            <div class="totalAmountArea">
              <div class="col-sm-4 col-sm-offset-8 col-xs-12">
                <ul class="list-unstyled">
                  <li>小計 <span>792円</span></li>
                  <li>消費税 <span>18円</span></li>
                  <li>総計 <span class="grandTotal">810円</span></li>
                </ul>
              </div>
            </div>
            <div class="checkBtnArea">
              <a href="checkout_step_1.html" class="btn btn-primary btn-block">購入する<i class="fa fa-arrow-circle-right" aria-hidden="true"></i></a>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/potepan/taxons/show.html.erb
<% provide(:title, @taxon.name) %>
<!-- LIGHT SECTION -->
<section class="lightSection clearfix pageHeader">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <div class="page-title">
          <h2><%= @taxon.name %></h2>
        </div>
      </div>
      <div class="col-xs-6">
        <ol class="breadcrumb pull-right">
          <li>
            <a href="/potepan/index.html">Home</a>
          </li>
          <li>
            <a href="#">shop</a>
          </li>
          <% @taxon.ancestors.each do |taxon| %>
            <li>
              <%= link_to taxon.name, potepan_category_path(taxon.id) %>
            </li>
          <% end %>
          <li class="active"><%= @taxon.name %></li>
        </ol>
      </div>
    </div>
  </div>
</section>
<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix productsContent">
  <div class="container">
    <div class="row">
      <div class="col-md-3 col-sm-4 col-xs-12 sideBar">
        <div class="panel panel-default">
          <div class="panel-heading">商品カテゴリー</div>
          <div class="panel-body">
            <div class="collapse navbar-collapse navbar-ex1-collapse navbar-side-collapse">
              <ul class="nav navbar-nav side-nav">
                <% @taxons.roots.each do |category| %>
                  <li>
                    <a href="javascript:;" data-toggle="collapse" data-target="<%= "#category#{category.id}" %>"><%= category.name %><i class="fa fa-plus"></i></a>
                    <ul id="<%= "category#{category.id}" %>" class="collapse collapseItem">
                      <% category.descendants.each do |taxon| %>
                        <% unless taxon.products.size.zero? %>
                          <li>
                            <%= link_to potepan_category_path(taxon.id) do %>
                              <i class="fa fa-caret-right" aria-hidden="true"></i><%= taxon.name %>
                              <span>(<%= taxon.products.size %>)</span>
                            <% end %>
                          </li>
                        <% end %>
                      <% end %>
                    </ul>
                  </li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
        <div class="panel panel-default priceRange">
          <div class="panel-heading">値段から探す</div>
          <div class="panel-body clearfix">
            <div class="price-slider-inner">
              <span class="amount-wrapper">
                <input type="text" id="price-amount-1" readonly>
                <strong>-</strong>
                <input type="text" id="price-amount-2" readonly>
              </span>
              <div id="price-range"></div>
            </div>
            <input class="btn btn-default" type="submit" value="絞り込む">
          </div>
        </div>
        <div class="panel panel-default filterNormal">
          <div class="panel-heading">色から探す</div>
          <div class="panel-body">
            <ul class="list-unstyled">
              <li><a href="#">ブラック<span>(15)</span></a></li>
              <li><a href="#">ホワイト<span>(10)</span></a></li>
              <li><a href="#">レッド<span>(7)</span></a></li>
              <li><a href="#">ブルー<span>(12)</span></a></li>
              <li><a href="#">オレンジ<span>(12)</span></a></li>
            </ul>
          </div>
        </div>
        <div class="panel panel-default filterNormal">
          <div class="panel-heading">サイズから探す</div>
          <div class="panel-body">
            <ul class="list-unstyled clearfix">
              <li><a href="#">S<span>(15)</span></a></li>
              <li><a href="#">M<span>(10)</span></a></li>
              <li><a href="#">L<span>(7)</span></a></li>
              <li><a href="#">XL<span>(12)</span></a></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="col-md-9 col-sm-8 col-xs-12">
        <div class="row filterArea">
          <div class="col-xs-6">
            <select name="guiest_id1" id="guiest_id1" class="select-drop">
              <option value="0">並び替え</option>
              <option value="1">人気順</option>
              <option value="2">安い順</option>
              <option value="3">新着順</option>
              <option value="3">高い順</option>
            </select>
          </div>
          <div class="col-xs-6">
            <div class="btn-group pull-right" role="group">
              <button type="button" class="btn btn-default active" onclick="window.location.href='product_grid_left_sidebar.html'"><i class="fa fa-th" aria-hidden="true"></i><span>Grid</span></button>
              <button type="button" class="btn btn-default" onclick="window.location.href='product_list_left_sidebar.html'"><i class="fa fa-th-list" aria-hidden="true"></i><span>List</span></button>
            </div>
          </div>
        </div>
        <div class="row">
          <% @products.each do |product| %>
            <div class="col-sm-4 col-xs-12">
              <div class="productBox">
                <div class="productImage clearfix">
                  <%= image_tag(product.display_image.attachment.url(:product), alt: product.display_image.alt) %>
                  <div class="productMasking">
                    <ul class="list-inline btn-group" role="group">
                      <li><a data-toggle="modal" href=".login-modal" class="btn btn-default"><i class="fa fa-heart"></i></a></li>
                      <li><a href="cart_page.html" class="btn btn-default"><i class="fa fa-shopping-cart"></i></a></li>
                      <li><a class="btn btn-default" data-toggle="modal" href=".quick-view" ><i class="fa fa-eye"></i></a></li>
                    </ul>
                  </div>
                </div>
                <div class="productCaption clearfix">
                  <%= link_to potepan_product_path(product.id) do %>
                    <h5><%= product.name %></h5>
                  <% end %>
                  <h3><%= product.display_price %></h3>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- LIGHT SECTION -->
<section class="lightSection clearfix">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="owl-carousel partnersLogoSlider">
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-01.png", alt: "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-02.png", alt: "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-03.png", alt: "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-04.png", alt: "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-05.png", alt: "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-01.png", alt: "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-02.png", alt: "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-03.png", alt: "partner-img") %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>